vm:
    name: pxl-web-vagrant
    ip: 192.168.1.99
    memory: 1024
    cpus: 1
    locale:
        timezone: UTC
        language-iso: en_US
    provision:
        show-command: true
        show-command-output: false
        show-command-execution-time: true
        show-command-exit-code: false
        abort-on-error: false
    home-dir: /home/vagrant
web-servers:
    apache:
        enabled: true
        port: 7001
    nginx:
        enabled: true
        port: 7002
code:
    php:
        versions:
            - 7.3
            - 7.2
            - 7.1
            - 7.0
            - 5.6
        modules:
        cache:
            memcached:
                enabled: true
            apc:
                enabled: true
databases:
    mysql:
        enabled: true
        version: 5.7
    postgresql:
        enabled: true
cache:
    redis:
        enabled: true
shell:
    tmux:
        enabled: true
        version: 2.8
        tmuxinator:
            enabled: true
        gpakosz:
            enabled: true
    liquidprompt:
        enabled: true
