debug: true
timezone: 'America/Los_Angeles'
vm:
    name: 'pxl-web-vagrant'
    memory: 1024
network:
    ip: '192.168.99.96'
web-servers:
    apache:
        enabled: false
        port: 7002
    nginx:
        enabled: true
        port: 7003
code:
    php:
        enabled: true
        versions:
            - 7.3
        modules:
            - gzip
        cache:
            memcached: false
            apc: false
databases:
    mysql:
        enabled: true
    mongodb:
        enabled: false
cache:
    redis:
        enabled: false
shell:
    tmux:
        enabled: true
        version: 2.8
        tmuxinator:
            enabled: true
        gpakosz:
            enabled: true
    liquidprompt:
        enabled: true
