vm:
    name: pxl-web-vagrant
    ip: 192.168.88.99
    memory: auto
    cpus: 1
    locale:
        timezone: UTC
        language-iso: en_US
    provision:
        show-command: true
        show-command-output: false
        show-command-execution-time: true
        show-command-exit-code: false
        abort-on-error: false
        upgrade-apt: true
    home-dir: /vagrant/projects
    projects-dir: /vagrant/projects
    backup-on-destroy: true
web-servers:
    apache:
        enabled: true
        port:
            http: 7001
            https: 7002
    nginx:
        enabled: false
        port:
            http: 8001
            https: 8002
code:
    php:
        versions:
            - 7.3
            - 7.2
            - 7.1
            - 7.0
            - 5.6
        modules:
        cache:
            memcached:
                enabled: true
            apc:
                enabled: true
        xdebug:
            enabled: true
databases:
    mysql:
        enabled: true
        version: 5.7
        phpmyadmin: true
    postgresql:
        enabled: false
cache:
    redis:
        enabled: false
shell:
    tmux:
        enabled: true
        version: 2.8
        tmuxinator:
            enabled: true
            auto-start: home
        gpakosz:
            enabled: true
            statusbar-title: PXL Web Vagrant
    liquidprompt:
        enabled: true
